name: latest-youtube-videos
on:
  schedule:
    #Runs At 00:00 on every Sunday.
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows us to run workflow manually through the Github Actions Workflow page directly
jobs:
  update_videos_list:
    name: Update this repo's README with latest youtube videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Pull in latest youtube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBE
          feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCAgauq33hSuPU2lGLUkyC7A'
